version: "3.0"
services:
  adnev:
    image: schematch/adnev
    build: src/main/resources/adnev
    ports:
      - "127.0.0.1:5002:5002"
    volumes:
      - type: bind
        source: ./target/adnev
        target: /adnev/DSMA/target/adnev
  leapme:
    image: schematch/leapme
    build: src/main/resources/leapme
    ports:
      - "127.0.0.1:5000:5000"
    command:
      - "glove"
    volumes:
      - type: bind
        source: ./data
        target: /leapme/data
  embdi:
    image: schematch/embdi
    build: src/main/resources/embdi
    ports:
      - "127.0.0.1:5001:5001"
    volumes:
      - type: bind
        source: ./data
        target: /embdi/data
      - type: bind
        source: ./target/embdi_cache
        target: /embdi/cache