version: "3.0"
services:
  leapme:
    image: schematch/leapme
    build: src/main/resources/leapme
    ports:
      - "127.0.0.1:5000:5000"
    command:
      - "glove"
    volumes:
      - type: bind
        source: ./data
        target: /leapme/data
  embdi:
    image: schematch/embdi
    build: src/main/resources/embdi
    ports:
      - "127.0.0.1:5001:5001"
    volumes:
      - type: bind
        source: ./data
        target: /embdi/data
      - type: bind
        source: ./target/embdi_cache
        target: /embdi/cache
  ic-GALib:
    image: schematch/ic-galib
    build: src/main/resources/ic-GALib
    ports:
      - "127.0.0.1:5003:5003"
    volumes:
      - type: bind
        source: ./target
        target: /ic/target
  ic-graspologic:
    image: schematch/ic-graspologic
    build: src/main/resources/ic-graspologic
    ports:
      - "127.0.0.1:5004:5004"
    volumes:
      - type: bind
        source: ./target
        target: /ic/target